parameters:
    app.default_sender: '%env(APP_DEFAULT_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite pour JWTService (optionnelle, car autowire est activé)
    App\Service\JWTService:
        arguments:
            $secret: '%env(APP_JWTSECRET)%'
    
    App\Service\ProfileCompletionService: ~
    App\Service\GeolocationService: ~

    App\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }